import { createFileRoute, Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { useState } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  LineChart,
  Line,
  AreaChart,
  Area,
  Legend,
  RadarChart,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  Radar,
  Cell,
} from "recharts";
import {
  ArrowLeft,
  BarChart3,
  TrendingUp,
  Grid3x3,
  Brain,
  Layers,
  Sparkles,
  Map as MapIcon,
} from "lucide-react";
import { NA_VIEWBOX, NA_DEPARTMENTS } from "@/lib/na-geo";
import { TEMPORAL_META, TEMPORAL_ECO, TEMPORAL_POLITICAL } from "@/lib/temporal";
import { XGB_CURVE } from "@/lib/learning_curves";

export const Route = createFileRoute("/visualisation")({
  component: VisualisationPage,
});

/* ═══════════════════════════════════════════════════════════════════════
   DATA — based on the user's actual ML results from the notebook
   ═══════════════════════════════════════════════════════════════════════ */

// Model comparison data (ré-entraînement avec la délinquance — bruit 0.15, ~77%)
const modelComparison = [
  { name: "Logistic Reg.", accuracy: 76.76, precision: 76.85, recall: 76.76, f1: 76.75, fill: "#6366f1" },
  { name: "XGBoost", accuracy: 76.67, precision: 76.65, recall: 76.67, f1: 76.60, fill: "#8b5cf6" },
  { name: "Grad. Boost.", accuracy: 75.48, precision: 75.37, recall: 75.48, f1: 75.11, fill: "#a78bfa" },
  { name: "Random Forest", accuracy: 72.57, precision: 73.19, recall: 72.57, f1: 71.22, fill: "#c4b5fd" },
  { name: "SVM (Linear)", accuracy: 66.69, precision: 67.22, recall: 66.69, f1: 62.95, fill: "#e0e7ff" },
];

// Radar chart data for multi-metric comparison
const radarData = [
  { metric: "Accuracy", "Logistic Reg.": 76.76, XGBoost: 76.67, "Random Forest": 72.57, "Grad. Boost.": 75.48, "SVM": 66.69 },
  { metric: "Precision", "Logistic Reg.": 76.85, XGBoost: 76.65, "Random Forest": 73.19, "Grad. Boost.": 75.37, "SVM": 67.22 },
  { metric: "Recall", "Logistic Reg.": 76.76, XGBoost: 76.67, "Random Forest": 72.57, "Grad. Boost.": 75.48, "SVM": 66.69 },
  { metric: "F1-Score", "Logistic Reg.": 76.75, XGBoost: 76.60, "Random Forest": 71.22, "Grad. Boost.": 75.11, "SVM": 62.95 },
];

// Correlation heatmap data — VRAIES corrélations de Pearson calculées sur les données
// (indicateurs delta_ + score économique du modèle, avec délinquance intégrée).
const corrVariables = [
  "Délinquance",
  "Chômage",
  "Emploi",
  "Activité",
  "Population",
  "Logement",
  "Entreprises",
  "Score éco",
];

// Matrice de corrélation réelle (8×8) — la ligne/colonne "Score éco" révèle les facteurs
// les plus déterminants : Délinquance −0,70, Population +0,40, Logement +0,26, Activité +0,24.
const corrMatrix: number[][] = [
  [1.00, -0.01, -0.01, 0.01, -0.06, 0.08, -0.00, -0.70],
  [-0.01, 1.00, -0.04, -0.05, -0.02, 0.05, -0.03, 0.04],
  [-0.01, -0.04, 1.00, 0.00, -0.01, -0.05, -0.05, 0.08],
  [0.01, -0.05, 0.00, 1.00, 0.04, -0.08, 0.13, 0.24],
  [-0.06, -0.02, -0.01, 0.04, 1.00, 0.03, 0.01, 0.40],
  [0.08, 0.05, -0.05, -0.08, 0.03, 1.00, -0.10, 0.26],
  [-0.00, -0.03, -0.05, 0.13, 0.01, -0.10, 1.00, -0.04],
  [-0.70, 0.04, 0.08, 0.24, 0.40, 0.26, -0.04, 1.00],
];

// Per-class metrics XGBoost (ré-entraînement avec délinquance — 5 classes)
const perClassMetrics = [
  { classe: "Crise",      precision: 90.6, recall: 86.1, f1: 88.3 },
  { classe: "Déclin",     precision: 67.1, recall: 62.4, f1: 64.7 },
  { classe: "Stable",     precision: 79.5, recall: 84.0, f1: 81.7 },
  { classe: "Croissance", precision: 66.8, recall: 67.4, f1: 67.1 },
  { classe: "Boom",       precision: 79.9, recall: 73.9, f1: 76.8 },
];

// CV 5-fold scores XGBoost (ré-entraînement avec délinquance — moyenne 76,59% ±0,08)
const cvFoldScores = [
  { fold: "Fold 1", accuracy: 76.47, fill: "#6366f1" },
  { fold: "Fold 2", accuracy: 76.63, fill: "#7c3aed" },
  { fold: "Fold 3", accuracy: 76.57, fill: "#8b5cf6" },
  { fold: "Fold 4", accuracy: 76.58, fill: "#a78bfa" },
  { fold: "Fold 5", accuracy: 76.71, fill: "#c4b5fd" },
];

// Temporal projections (TEMPORAL_ECO / TEMPORAL_POLITICAL) are generated by the
// real XGBoost model — see src/lib/temporal.ts and ml/scenarios/gen_temporal.py.

// Couleurs par bloc politique (cohérentes avec le mapping ECO_SCENARIOS)
const BLOC_COLORS: Record<string, string> = {
  Centre: "#3b82f6", // Macron
  Droite: "#8b5cf6", // Pécresse
  Gauche: "#ef4444", // Mélenchon
  RN:     "#92400e", // Le Pen
};
const SCENARIO_META = [
  { key: "optimiste" as const,  label: "Optimiste",  color: "#10b981", note: "croissance (+0,2σ/an)" },
  { key: "neutre" as const,     label: "Neutre",     color: "#94a3b8", note: "statu quo" },
  { key: "pessimiste" as const, label: "Pessimiste", color: "#f59e0b", note: "déclin (−0,2σ/an)" },
];

// Department-level prediction results (from notebook → predictions.json), keyed by INSEE code
const deptPredByCode: Record<string, { proba: number; predicted: string; real: string; correct: boolean }> = {
  "16": { proba: 86.5, predicted: "MACRON", real: "MACRON", correct: true  },
  "17": { proba: 87.7, predicted: "MACRON", real: "MACRON", correct: true  },
  "19": { proba: 96.4, predicted: "MACRON", real: "MACRON", correct: true  },
  "23": { proba: 91.4, predicted: "MACRON", real: "MACRON", correct: true  },
  "24": { proba: 95.5, predicted: "MACRON", real: "MACRON", correct: true  },
  "33": { proba: 1.9,  predicted: "LE PEN", real: "MACRON", correct: false },
  "40": { proba: 92.7, predicted: "MACRON", real: "MACRON", correct: true  },
  "47": { proba: 92.9, predicted: "MACRON", real: "LE PEN", correct: false },
  "64": { proba: 96.4, predicted: "MACRON", real: "MACRON", correct: true  },
  "79": { proba: 87.7, predicted: "MACRON", real: "MACRON", correct: true  },
  "86": { proba: 93.4, predicted: "MACRON", real: "MACRON", correct: true  },
  "87": { proba: 96.7, predicted: "MACRON", real: "MACRON", correct: true  },
};

// Choropleth fill: probability ~0–100% → light → deep blue (MACRON / Centre)
function deptFill(proba: number): string {
  const t = Math.min(1, Math.max(0, proba / 100));
  const lightness = Math.round(85 - t * 47);
  return `hsl(214, 70%, ${lightness}%)`;
}

/* ═══════════════════════════════════════════════════════════════════════
   HELPERS
   ═══════════════════════════════════════════════════════════════════════ */

/**
 * Map a correlation value from [-1, 1] to a clean diverging scale
 * deep blue (−1) → white (0) → deep red (+1) (ColorBrewer RdBu endpoints).
 * Near-zero values are white, matching the legend.
 */
function corrColor(value: number): string {
  const t = Math.min(1, Math.abs(value));
  // Endpoints: white (247,247,247), red (178,24,43), blue (33,102,172)
  const [er, eg, eb] = value >= 0 ? [178, 24, 43] : [33, 102, 172];
  const r = Math.round(247 + (er - 247) * t);
  const g = Math.round(247 + (eg - 247) * t);
  const b = Math.round(247 + (eb - 247) * t);
  return `rgb(${r}, ${g}, ${b})`;
}

/** Animated container variant */
const containerVariant = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.08 } },
};
const itemVariant = {
  hidden: { opacity: 0, y: 24 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5 } },
};

/* ═══════════════════════════════════════════════════════════════════════
   COMPONENTS
   ═══════════════════════════════════════════════════════════════════════ */

function SectionCard({
  title,
  icon,
  children,
  className = "",
}: {
  title: string;
  icon: React.ReactNode;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <motion.section
      variants={itemVariant}
      className={`rounded-lg border border-border bg-card p-5 md:p-6 shadow-sm ${className}`}
    >
      <div className="mb-4 flex items-center gap-3">
        <div className="flex h-9 w-9 items-center justify-center rounded-md bg-primary/10 text-primary">
          {icon}
        </div>
        <h2 className="font-serif text-base font-bold tracking-tight text-foreground">{title}</h2>
      </div>
      {children}
    </motion.section>
  );
}

/** Tabs used to switch between different datasets within a chart card */
function ChartTabs({
  tabs,
  active,
  onChange,
}: {
  tabs: { id: string; label: string }[];
  active: string;
  onChange: (id: string) => void;
}) {
  return (
    <div className="mb-4 flex flex-wrap gap-1.5">
      {tabs.map((t) => (
        <button
          key={t.id}
          onClick={() => onChange(t.id)}
          className={`rounded-md border px-3 py-1.5 text-xs font-medium transition-colors duration-150 ${active === t.id
              ? "border-primary bg-primary text-primary-foreground shadow-sm"
              : "border-border bg-muted text-muted-foreground hover:bg-muted/80 hover:text-foreground"
            }`}
        >
          {t.label}
        </button>
      ))}
    </div>
  );
}

/* ═══════════════════════════════════════════════════════════════════════
   PAGE
   ═══════════════════════════════════════════════════════════════════════ */

function VisualisationPage() {
  const [activeMetric, setActiveMetric] = useState("accuracy");
  const [hoveredCell, setHoveredCell] = useState<{ r: number; c: number } | null>(null);
  const [hoveredDeptCode, setHoveredDeptCode] = useState<string | null>(null);

  const metricKey = activeMetric as keyof (typeof modelComparison)[0];
  const hoveredDeptInfo = hoveredDeptCode
    ? { geo: NA_DEPARTMENTS.find((d) => d.code === hoveredDeptCode)!, pred: deptPredByCode[hoveredDeptCode] }
    : null;

  return (
    <div className="min-h-screen text-foreground">
      {/* ────── Navigation ────── */}
      <nav className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur-sm">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-3">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-foreground font-bold text-sm">
              G
            </div>
            <div className="leading-tight">
              <p className="text-sm font-semibold text-foreground">GouvData</p>
              <p className="text-[11px] text-muted-foreground">
                Visualisation · Analyse prédictive
              </p>
            </div>
          </div>
          <Link
            to="/"
            className="inline-flex items-center gap-2 rounded-md border border-border bg-muted px-4 py-2 text-xs font-medium text-muted-foreground transition-colors hover:text-foreground hover:bg-muted/80"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            Retour au tableau de bord
          </Link>
        </div>
      </nav>

      {/* ────── Hero ────── */}
      <header className="border-b border-border">
        <div className="mx-auto max-w-7xl px-6 py-10 md:py-14">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="max-w-3xl"
          >
            <span className="inline-flex items-center gap-2 rounded-md border border-border bg-muted px-3 py-1 text-xs text-muted-foreground">
              <Sparkles className="h-3.5 w-3.5 text-primary" />
              Analyse complète · Résultats Machine Learning
            </span>
            <h1 className="mt-4 font-serif text-3xl font-bold tracking-tight text-foreground md:text-5xl">
              Visualisation des résultats
            </h1>
            <p className="mt-3 max-w-2xl text-sm text-muted-foreground md:text-base leading-relaxed">
              Corrélations entre variables, courbes d'apprentissage et
              comparaison multi-modèles sur les données socio-économiques de la
              Nouvelle-Aquitaine.
            </p>

            <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
              {[
                { label: "Meilleur score", value: "76.76%", sub: "Logistic Regression" },
                { label: "Variable n°1", value: "Délinquance", sub: "17,5% d'importance" },
                { label: "Validation croisée", value: "76,59%", sub: "5-fold (±0,08)" },
                { label: "Modèles comparés", value: "5", sub: "XGBoost, RF, GB, LR, SVM" },
              ].map((item) => (
                <div
                  key={item.label}
                  className="rounded-md border border-border bg-muted/50 p-4"
                >
                  <p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">
                    {item.label}
                  </p>
                  <p className="mt-2 text-xl font-bold text-foreground">
                    {item.value}
                  </p>
                  <p className="mt-1 text-xs text-muted-foreground">{item.sub}</p>
                </div>
              ))}
            </div>
          </motion.div>
        </div>
      </header>

      {/* ────── Main content ────── */}
      <motion.main
        variants={containerVariant}
        initial="hidden"
        animate="show"
        className="mx-auto max-w-7xl space-y-8 px-6 py-10"
      >
        {/* ╔══════ 1. Correlation Heatmap ══════╗ */}
        <SectionCard
          title="Matrice de Corrélation entre Variables"
          icon={<Grid3x3 className="h-5 w-5" />}
        >
          <p className="mb-4 text-xs text-muted-foreground">
            Corrélation de Pearson entre les indicateurs socio-économiques et l'état économique
            prédit. La colonne <strong>Score éco</strong> révèle les facteurs déterminants :
            la <strong>délinquance (−0,70)</strong> est la plus corrélée. Survolez une cellule pour la valeur exacte.
          </p>
          <div className="overflow-x-auto">
            <div className="mx-auto" style={{ minWidth: 580 }}>
              {/* Column headers */}
              <div className="flex">
                <div style={{ width: 120, minWidth: 120 }} />
                {corrVariables.map((v, ci) => (
                  <div
                    key={`h-${ci}`}
                    className="flex items-end justify-center text-[9px] md:text-[10px] font-medium text-muted-foreground"
                    style={{
                      width: 56,
                      minWidth: 56,
                      height: 72,
                      writingMode: "vertical-rl",
                      transform: "rotate(180deg)",
                    }}
                  >
                    {v}
                  </div>
                ))}
              </div>

              {/* Rows */}
              {corrVariables.map((rowVar, ri) => (
                <div key={`r-${ri}`} className="flex items-center">
                  <div
                    className="shrink-0 text-right pr-3 text-[10px] md:text-xs font-medium text-muted-foreground truncate"
                    style={{ width: 120, minWidth: 120 }}
                  >
                    {rowVar}
                  </div>
                  {corrVariables.map((_, ci) => {
                    const val = corrMatrix[ri][ci];
                    const isHovered =
                      hoveredCell?.r === ri && hoveredCell?.c === ci;
                    return (
                      <div
                        key={`c-${ri}-${ci}`}
                        className="relative transition-transform duration-150"
                        style={{
                          width: 56,
                          height: 40,
                          minWidth: 56,
                          backgroundColor: corrColor(val),
                          border: isHovered
                            ? "2px solid white"
                            : "1px solid rgba(0,0,0,0.08)",
                          borderRadius: 4,
                          margin: 1,
                          transform: isHovered ? "scale(1.15)" : "scale(1)",
                          zIndex: isHovered ? 10 : 0,
                          cursor: "crosshair",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                        }}
                        onMouseEnter={() => setHoveredCell({ r: ri, c: ci })}
                        onMouseLeave={() => setHoveredCell(null)}
                      >
                        <span
                          className="text-[9px] font-bold select-none"
                          style={{
                            color:
                              Math.abs(val) > 0.5
                                ? "white"
                                : "rgba(0,0,0,0.7)",
                            opacity: isHovered ? 1 : 0.6,
                          }}
                        >
                          {val.toFixed(2)}
                        </span>
                      </div>
                    );
                  })}
                </div>
              ))}

              {/* Legend */}
              <div className="mt-4 flex items-center gap-2 justify-center">
                <span className="text-[10px] text-muted-foreground">−1.0</span>
                <div
                  className="h-3 rounded-full"
                  style={{
                    width: 200,
                    background:
                      "linear-gradient(to right, rgb(50,70,190), rgb(180,200,220), white, rgb(220,180,170), rgb(180,60,50))",
                  }}
                />
                <span className="text-[10px] text-muted-foreground">+1.0</span>
              </div>
            </div>
          </div>
        </SectionCard>

        {/* ╔══════ 2. Model Performance Bar Chart ══════╗ */}
        <div className="grid gap-8 lg:grid-cols-2">
          <SectionCard
            title="Performance des Modèles (5 classes)"
            icon={<BarChart3 className="h-5 w-5" />}
          >
            <ChartTabs
              tabs={[
                { id: "accuracy", label: "Accuracy" },
                { id: "precision", label: "Precision" },
                { id: "recall", label: "Recall" },
                { id: "f1", label: "F1-Score" },
              ]}
              active={activeMetric}
              onChange={setActiveMetric}
            />
            <ResponsiveContainer width="100%" height={300}>
              <BarChart
                data={modelComparison}
                margin={{ top: 5, right: 10, left: -10, bottom: 5 }}
              >
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="#e2e8f0"
                />
                <XAxis
                  dataKey="name"
                  tick={{ fill: "#334155", fontSize: 11 }}
                  axisLine={{ stroke: "#cbd5e1" }}
                  tickLine={{ stroke: "#cbd5e1" }}
                />
                <YAxis
                  domain={[55, 90]}
                  tick={{ fill: "#334155", fontSize: 11 }}
                  axisLine={{ stroke: "#cbd5e1" }}
                  tickLine={{ stroke: "#cbd5e1" }}
                  tickFormatter={(v: number) => `${v}%`}
                />
                <Tooltip
                  contentStyle={{
                    background: "#ffffff",
                    border: "1px solid #e2e8f0",
                    borderRadius: 6,
                    color: "#1e293b",
                    fontSize: 12,
                  }}
                  formatter={(v: number | string | undefined) => [`${Number(v ?? 0).toFixed(2)}%`, activeMetric.charAt(0).toUpperCase() + activeMetric.slice(1)]}

                />
                <Bar dataKey={metricKey} radius={[4, 4, 0, 0]} barSize={36}>
                  {modelComparison.map((entry, idx) => (
                    <Cell key={`cell-${idx}`} fill={entry.fill} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </SectionCard>

          {/* Radar chart multi-metric */}
          <SectionCard
            title="Radar Multi-Métriques"
            icon={<Layers className="h-5 w-5" />}
          >
            <p className="mb-4 text-xs text-muted-foreground">
              Comparaison simultanée de toutes les métriques pour chaque modèle.
            </p>
            <ResponsiveContainer width="100%" height={340}>
              <RadarChart cx="50%" cy="50%" outerRadius="70%" data={radarData}>
                <PolarGrid stroke="#e2e8f0" />
                <PolarAngleAxis
                  dataKey="metric"
                  tick={{ fill: "#1e293b", fontSize: 11, fontWeight: 500 }}
                />
                <PolarRadiusAxis
                  angle={30}
                  domain={[60, 85]}
                  tick={{ fill: "#64748b", fontSize: 9 }}
                />
                <Radar
                  name="Logistic Reg."
                  dataKey="Logistic Reg."
                  stroke="#4338ca"
                  fill="#4338ca"
                  fillOpacity={0.12}
                  strokeWidth={2}
                />
                <Radar
                  name="XGBoost"
                  dataKey="XGBoost"
                  stroke="#7c3aed"
                  fill="#7c3aed"
                  fillOpacity={0.08}
                  strokeWidth={2}
                />
                <Radar
                  name="Random Forest"
                  dataKey="Random Forest"
                  stroke="#2563eb"
                  fill="#2563eb"
                  fillOpacity={0.06}
                  strokeWidth={1.5}
                />
                <Radar
                  name="SVM"
                  dataKey="SVM"
                  stroke="#94a3b8"
                  fill="#94a3b8"
                  fillOpacity={0.04}
                  strokeWidth={1}
                  strokeDasharray="4 4"
                />
                <Legend
                  wrapperStyle={{ fontSize: 10, color: "#475569" }}
                />
                <Tooltip
                  contentStyle={{
                    background: "#ffffff",
                    border: "1px solid #e2e8f0",
                    borderRadius: 6,
                    color: "#1e293b",
                    fontSize: 11,
                  }}
                />
              </RadarChart>
            </ResponsiveContainer>
          </SectionCard>
        </div>

        {/* ╔══════ 3. Training Curves ══════╗ */}
        <SectionCard
          title="Courbes d'Apprentissage"
          icon={<TrendingUp className="h-5 w-5" />}
        >
          <p className="mb-4 text-xs text-muted-foreground">
            Modèle <strong>XGBoost</strong> — évolution réelle sur les 100 itérations de boosting
            (équivalent des epochs). La courbe d'entraînement (bleu) progresse au-dessus de la
            validation (orange) : c'est l'écart d'apprentissage classique.
          </p>
          <div className="grid gap-6 lg:grid-cols-2">
            {/* Accuracy */}
            <div>
              <h3 className="mb-3 text-sm font-medium text-muted-foreground">
                Courbes de Précision
              </h3>
              <ResponsiveContainer width="100%" height={260}>
                <LineChart
                  data={XGB_CURVE}
                  margin={{ top: 5, right: 10, left: -10, bottom: 5 }}
                >
                  <CartesianGrid
                    strokeDasharray="3 3"
                    stroke="#e2e8f0"
                  />
                  <XAxis
                    dataKey="epoch"
                    tick={{ fill: "#334155", fontSize: 10 }}
                    tickLine={{ stroke: "#cbd5e1" }}
                    axisLine={{ stroke: "#cbd5e1" }}
                    label={{
                      value: "Itération",
                      position: "insideBottomRight",
                      offset: -5,
                      style: { fill: "#475569", fontSize: 10 },
                    }}
                  />
                  <YAxis
                    domain={[0.6, 0.85]}
                    tick={{ fill: "#334155", fontSize: 10 }}
                    tickLine={{ stroke: "#cbd5e1" }}
                    axisLine={{ stroke: "#cbd5e1" }}
                    label={{
                      value: "Accuracy",
                      angle: -90,
                      position: "insideLeft",
                      offset: 15,
                      style: { fill: "#475569", fontSize: 10 },
                    }}
                  />
                  <Tooltip
                    contentStyle={{
                      background: "#ffffff",
                      border: "1px solid #e2e8f0",
                      borderRadius: 6,
                      color: "#1e293b",
                      fontSize: 11,
                    }}
                  />
                  <Legend
                    wrapperStyle={{
                      fontSize: 11,
                      color: "#475569",
                    }}
                  />
                  <Line
                    type="monotone"
                    dataKey="trainAcc"
                    name="Train"
                    stroke="#6366f1"
                    strokeWidth={2.5}
                    dot={false}
                    activeDot={{ r: 4, stroke: "#6366f1" }}
                  />
                  <Line
                    type="monotone"
                    dataKey="valAcc"
                    name="Validation"
                    stroke="#f59e0b"
                    strokeWidth={2}
                    dot={false}
                    activeDot={{ r: 4, stroke: "#f59e0b" }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>

            {/* Loss */}
            <div>
              <h3 className="mb-3 text-sm font-medium text-muted-foreground">
                Courbes de Perte
              </h3>
              <ResponsiveContainer width="100%" height={260}>
                <LineChart
                  data={XGB_CURVE}
                  margin={{ top: 5, right: 10, left: -10, bottom: 5 }}
                >
                  <CartesianGrid
                    strokeDasharray="3 3"
                    stroke="#e2e8f0"
                  />
                  <XAxis
                    dataKey="epoch"
                    tick={{ fill: "#334155", fontSize: 10 }}
                    tickLine={{ stroke: "#cbd5e1" }}
                    axisLine={{ stroke: "#cbd5e1" }}
                    label={{
                      value: "Itération",
                      position: "insideBottomRight",
                      offset: -5,
                      style: { fill: "#475569", fontSize: 10 },
                    }}
                  />
                  <YAxis
                    domain={[0.4, 1.5]}
                    tick={{ fill: "#334155", fontSize: 10 }}
                    tickLine={{ stroke: "#cbd5e1" }}
                    axisLine={{ stroke: "#cbd5e1" }}
                    label={{
                      value: "Loss",
                      angle: -90,
                      position: "insideLeft",
                      offset: 15,
                      style: { fill: "#475569", fontSize: 10 },
                    }}
                  />
                  <Tooltip
                    contentStyle={{
                      background: "#ffffff",
                      border: "1px solid #e2e8f0",
                      borderRadius: 6,
                      color: "#1e293b",
                      fontSize: 11,
                    }}
                  />
                  <Legend
                    wrapperStyle={{
                      fontSize: 11,
                      color: "#475569",
                    }}
                  />
                  <Line
                    type="monotone"
                    dataKey="trainLoss"
                    name="Train"
                    stroke="#6366f1"
                    strokeWidth={2.5}
                    dot={false}
                    activeDot={{ r: 4, stroke: "#6366f1" }}
                  />
                  <Line
                    type="monotone"
                    dataKey="valLoss"
                    name="Validation"
                    stroke="#f59e0b"
                    strokeWidth={2}
                    dot={false}
                    activeDot={{ r: 4, stroke: "#f59e0b" }}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
          <div className="mt-4 rounded-md border border-emerald-600/30 bg-emerald-50 px-4 py-3 text-xs text-emerald-800">
            <strong>Lecture :</strong> l'accuracy d'entraînement monte à <strong>82,3 %</strong> tandis
            que la validation se stabilise à <strong>75,8 %</strong> (≈ accuracy test). La perte (log-loss)
            chute de 1,41 à 0,42 (train) / 0,56 (validation). L'écart modéré train/validation confirme
            un apprentissage sain, sans surapprentissage excessif.
          </div>
        </SectionCard>

        {/* ╔══════ 4. Performance par classe + CV folds ══════╗ */}
        <div className="grid gap-8 lg:grid-cols-2">
          <SectionCard
            title="Performance XGBoost par classe"
            icon={<Brain className="h-5 w-5" />}
          >
            <p className="mb-4 text-xs text-muted-foreground">
              Précision, Rappel et F1-Score pour chacune des 5 classes prédites
              (jeu de test — 171 605 observations).
            </p>
            <ResponsiveContainer width="100%" height={280}>
              <BarChart
                data={perClassMetrics}
                margin={{ top: 5, right: 10, left: -10, bottom: 5 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                <XAxis
                  dataKey="classe"
                  tick={{ fill: "#334155", fontSize: 11 }}
                  axisLine={{ stroke: "#cbd5e1" }}
                  tickLine={{ stroke: "#cbd5e1" }}
                />
                <YAxis
                  domain={[60, 95]}
                  tick={{ fill: "#334155", fontSize: 10 }}
                  axisLine={{ stroke: "#cbd5e1" }}
                  tickLine={{ stroke: "#cbd5e1" }}
                  tickFormatter={(v) => `${v}%`}
                />
                <Tooltip
                  contentStyle={{
                    background: "#ffffff",
                    border: "1px solid #e2e8f0",
                    borderRadius: 6,
                    color: "#1e293b",
                    fontSize: 12,
                  }}
                  formatter={(v) => [`${Number(v).toFixed(1)}%`]}
                />
                <Legend wrapperStyle={{ fontSize: 11, color: "#475569" }} />
                <Bar dataKey="precision" name="Précision" fill="#6366f1" radius={[4, 4, 0, 0]} barSize={22} />
                <Bar dataKey="recall"    name="Rappel"    fill="#8b5cf6" radius={[4, 4, 0, 0]} barSize={22} />
                <Bar dataKey="f1"        name="F1-Score"  fill="#a78bfa" radius={[4, 4, 0, 0]} barSize={22} />
              </BarChart>
            </ResponsiveContainer>
          </SectionCard>

          <SectionCard
            title="Validation croisée 5-fold — XGBoost"
            icon={<Brain className="h-5 w-5" />}
          >
            <p className="mb-4 text-xs text-muted-foreground">
              Accuracy par fold — Moyenne : <strong>76,59 %</strong> (±0,08 %).
              Faible variance = modèle stable et généralisable.
            </p>
            <ResponsiveContainer width="100%" height={280}>
              <BarChart
                data={cvFoldScores}
                margin={{ top: 5, right: 10, left: -10, bottom: 5 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                <XAxis
                  dataKey="fold"
                  tick={{ fill: "#334155", fontSize: 11 }}
                  axisLine={{ stroke: "#cbd5e1" }}
                  tickLine={{ stroke: "#cbd5e1" }}
                />
                <YAxis
                  domain={[75, 78]}
                  tick={{ fill: "#334155", fontSize: 10 }}
                  axisLine={{ stroke: "#cbd5e1" }}
                  tickLine={{ stroke: "#cbd5e1" }}
                  tickFormatter={(v) => `${v}%`}
                />
                <Tooltip
                  contentStyle={{
                    background: "#ffffff",
                    border: "1px solid #e2e8f0",
                    borderRadius: 6,
                    color: "#1e293b",
                    fontSize: 12,
                  }}
                  formatter={(v) => [`${Number(v).toFixed(2)}%`, "Accuracy"]}
                />
                <Bar dataKey="accuracy" radius={[4, 4, 0, 0]} barSize={44}>
                  {cvFoldScores.map((entry, idx) => (
                    <Cell key={`cv-${idx}`} fill={entry.fill} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </SectionCard>
        </div>

        {/* ╔══════ Carte géographique Nouvelle-Aquitaine ══════╗ */}
        <SectionCard
          title="Carte des Prédictions — Nouvelle-Aquitaine"
          icon={<MapIcon className="h-5 w-5" />}
        >
          <p className="mb-3 text-xs text-muted-foreground">
            Résultat prédit par XGBoost pour la présidentielle 2022, par département.
            L'intensité du bleu reflète la probabilité de victoire MACRON / Centre.{" "}
            <span className="font-semibold text-amber-700">Contour orange</span> = prédiction
            erronée (le réel diffère du prédit). Survolez un département pour le détail.
          </p>

          <div className="grid items-start gap-6 md:grid-cols-[1.3fr_1fr]">
            {/* Carte SVG */}
            <div className="overflow-hidden rounded-md border border-border bg-muted/20 p-2">
              <svg viewBox={NA_VIEWBOX} className="mx-auto block h-auto w-full" style={{ maxHeight: 520 }}>
                {NA_DEPARTMENTS.map((dep) => {
                  const pred = deptPredByCode[dep.code];
                  const isHov = hoveredDeptCode === dep.code;
                  return (
                    <path
                      key={dep.code}
                      d={dep.d}
                      fill={pred ? deptFill(pred.proba) : "#e2e8f0"}
                      stroke={!pred?.correct ? "#f59e0b" : isHov ? "#0f172a" : "#ffffff"}
                      strokeWidth={!pred?.correct ? 3 : isHov ? 2 : 1}
                      style={{ cursor: "pointer", transition: "fill 120ms" }}
                      onMouseEnter={() => setHoveredDeptCode(dep.code)}
                      onMouseLeave={() => setHoveredDeptCode(null)}
                    />
                  );
                })}
                {/* Codes département */}
                {NA_DEPARTMENTS.map((dep) => (
                  <text
                    key={`t-${dep.code}`}
                    x={dep.cx}
                    y={dep.cy}
                    textAnchor="middle"
                    dominantBaseline="middle"
                    fontSize={16}
                    fontWeight="bold"
                    fill={(deptPredByCode[dep.code]?.proba ?? 0) > 65 ? "#ffffff" : "#1e293b"}
                    style={{ pointerEvents: "none" }}
                  >
                    {dep.code}
                  </text>
                ))}
              </svg>
            </div>

            {/* Panneau latéral : légende + détail survol */}
            <div className="space-y-4">
              <div className="rounded-md border border-border bg-muted/30 p-4">
                <p className="mb-2 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                  Probabilité MACRON / Centre
                </p>
                <div
                  className="h-3 w-full rounded-sm"
                  style={{ background: "linear-gradient(to right, hsl(214,70%,80%), hsl(214,70%,38%))" }}
                />
                <div className="mt-1 flex justify-between text-[10px] text-muted-foreground">
                  <span>0 %</span>
                  <span>100 %</span>
                </div>
                <div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground">
                  <span className="inline-block h-3 w-5 rounded-sm border-[3px] border-amber-500 bg-blue-200" />
                  Prédiction erronée (réel ≠ prédit)
                </div>
              </div>

              {hoveredDeptInfo ? (
                <div className="rounded-md border border-border bg-card p-4 shadow-sm">
                  <p className="text-sm font-bold text-foreground">
                    {hoveredDeptInfo.geo.code} — {hoveredDeptInfo.geo.nom}
                  </p>
                  {hoveredDeptInfo.pred ? (
                    <dl className="mt-2 space-y-1.5 text-xs">
                      <div className="flex justify-between gap-4">
                        <dt className="text-muted-foreground">Prédit</dt>
                        <dd className="font-semibold text-foreground">{hoveredDeptInfo.pred.predicted}</dd>
                      </div>
                      <div className="flex justify-between gap-4">
                        <dt className="text-muted-foreground">Réel</dt>
                        <dd className={`font-semibold ${hoveredDeptInfo.pred.correct ? "text-foreground" : "text-amber-700"}`}>
                          {hoveredDeptInfo.pred.real}
                        </dd>
                      </div>
                      <div className="flex justify-between gap-4">
                        <dt className="text-muted-foreground">Probabilité MACRON</dt>
                        <dd className="font-semibold text-foreground">{hoveredDeptInfo.pred.proba.toFixed(1)} %</dd>
                      </div>
                      <div className="flex justify-between gap-4">
                        <dt className="text-muted-foreground">Statut</dt>
                        <dd className={`font-semibold ${hoveredDeptInfo.pred.correct ? "text-emerald-700" : "text-amber-700"}`}>
                          {hoveredDeptInfo.pred.correct ? "✓ Correct" : "✗ Erroné"}
                        </dd>
                      </div>
                    </dl>
                  ) : (
                    <p className="mt-2 text-xs text-muted-foreground">Aucune donnée de prédiction.</p>
                  )}
                </div>
              ) : (
                <div className="rounded-md border border-dashed border-border bg-muted/20 p-4 text-center text-xs text-muted-foreground">
                  Survolez un département pour afficher le détail de la prédiction.
                </div>
              )}

              <div className="rounded-md border border-border bg-muted/30 p-4 text-xs text-muted-foreground">
                <strong className="text-foreground">10/12 départements</strong> correctement prédits.
                2 erreurs : le <strong className="text-amber-700">Lot-et-Garonne (47)</strong> (prédit MACRON, réel LE PEN)
                et la <strong className="text-amber-700">Gironde (33)</strong> — sa forte délinquance pousse le modèle
                vers le RN alors qu'elle a voté MACRON, illustrant que l'insécurité n'est pas le facteur décisif ici.
              </div>
            </div>
          </div>
        </SectionCard>

        {/* ╔══════ Projections temporelles 1/2/3 ans (modèle XGBoost) ══════╗ */}
        <SectionCard
          title="Projections Temporelles · Scénarios à 1, 2 et 3 ans"
          icon={<TrendingUp className="h-5 w-5" />}
        >
          <p className="mb-2 text-xs text-muted-foreground">
            Trois trajectoires économiques sont injectées dans le <strong>modèle XGBoost</strong> :
            on décale le vecteur d'indicateurs socio-économiques 2022 de la région, puis le modèle
            prédit l'orientation politique à 1, 2 et 3 ans. <span className="italic">Aucune valeur n'est
            posée à la main : la conversion économie → vote est produite par le modèle.</span>
          </p>

          {/* Légende scénarios */}
          <div className="mb-5 flex flex-wrap gap-4 text-xs">
            {SCENARIO_META.map((s) => (
              <span key={s.key} className="flex items-center gap-1.5">
                <span className="inline-block h-2.5 w-6 rounded-sm" style={{ background: s.color }} />
                <strong style={{ color: s.color }}>{s.label}</strong>
                <span className="text-muted-foreground">— {s.note}</span>
              </span>
            ))}
          </div>

          {/* 1. Indice économique projeté (le moteur) */}
          <h3 className="mb-3 text-sm font-medium text-muted-foreground">
            1 · Indice économique régional projeté (0–10) — espérance du modèle
          </h3>
          <ResponsiveContainer width="100%" height={250}>
            <LineChart data={TEMPORAL_ECO} margin={{ top: 5, right: 12, left: -10, bottom: 5 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
              <XAxis dataKey="annee" tick={{ fill: "#334155", fontSize: 11 }} tickLine={{ stroke: "#cbd5e1" }} axisLine={{ stroke: "#cbd5e1" }} />
              <YAxis domain={[0, 10]} tick={{ fill: "#334155", fontSize: 10 }} tickLine={{ stroke: "#cbd5e1" }} axisLine={{ stroke: "#cbd5e1" }} />
              <Tooltip contentStyle={{ background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: 6, color: "#1e293b", fontSize: 11 }} formatter={(v) => [`${Number(v ?? 0).toFixed(2)} / 10`, ""]} />
              <Legend wrapperStyle={{ fontSize: 11, color: "#475569" }} />
              <Line type="monotone" dataKey="optimiste"  name="Optimiste"  stroke="#10b981" strokeWidth={2.5} dot={{ r: 4 }} activeDot={{ r: 6 }} />
              <Line type="monotone" dataKey="neutre"     name="Neutre"     stroke="#94a3b8" strokeWidth={2} strokeDasharray="6 3" dot={{ r: 4 }} activeDot={{ r: 6 }} />
              <Line type="monotone" dataKey="pessimiste" name="Pessimiste" stroke="#f59e0b" strokeWidth={2.5} dot={{ r: 4 }} activeDot={{ r: 6 }} />
            </LineChart>
          </ResponsiveContainer>

          {/* 2. Conséquence politique : composition du vote prédit par scénario */}
          <h3 className="mb-1 mt-7 text-sm font-medium text-muted-foreground">
            2 · Conséquence politique — composition du vote prédit (%)
          </h3>
          <div className="mb-3 flex flex-wrap gap-3 text-[11px]">
            {Object.entries(BLOC_COLORS).map(([bloc, color]) => (
              <span key={bloc} className="flex items-center gap-1.5">
                <span className="inline-block h-2.5 w-2.5 rounded-sm" style={{ background: color }} />
                <span className="text-muted-foreground">
                  {bloc}
                  {bloc === "Centre" ? " (Macron)" : bloc === "Droite" ? " (Pécresse)" : bloc === "Gauche" ? " (Mélenchon)" : " (Le Pen)"}
                </span>
              </span>
            ))}
          </div>

          <div className="grid gap-5 md:grid-cols-3">
            {SCENARIO_META.map((s) => {
              const w = TEMPORAL_META.winners[s.key];
              return (
                <div key={s.key} className="rounded-md border border-border bg-muted/20 p-3">
                  <div className="mb-2 flex items-center justify-between">
                    <span className="text-xs font-semibold" style={{ color: s.color }}>{s.label}</span>
                    <span className="rounded-sm px-2 py-0.5 text-[10px] font-medium text-white" style={{ background: BLOC_COLORS[w.famille] }}>
                      +3 ans : {w.candidat}
                    </span>
                  </div>
                  <ResponsiveContainer width="100%" height={190}>
                    <AreaChart data={TEMPORAL_POLITICAL[s.key]} margin={{ top: 5, right: 5, left: -22, bottom: 0 }} stackOffset="expand">
                      <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                      <XAxis dataKey="annee" tick={{ fill: "#334155", fontSize: 9 }} tickLine={{ stroke: "#cbd5e1" }} axisLine={{ stroke: "#cbd5e1" }} />
                      <YAxis tickFormatter={(v: number) => `${Math.round(v * 100)}%`} tick={{ fill: "#334155", fontSize: 9 }} tickLine={{ stroke: "#cbd5e1" }} axisLine={{ stroke: "#cbd5e1" }} />
                      <Tooltip contentStyle={{ background: "#ffffff", border: "1px solid #e2e8f0", borderRadius: 6, color: "#1e293b", fontSize: 11 }} formatter={(v) => [`${Number(v ?? 0).toFixed(1)} %`, ""]} />
                      <Area type="monotone" dataKey="Centre" stackId="1" stroke={BLOC_COLORS.Centre} fill={BLOC_COLORS.Centre} fillOpacity={0.85} />
                      <Area type="monotone" dataKey="Droite" stackId="1" stroke={BLOC_COLORS.Droite} fill={BLOC_COLORS.Droite} fillOpacity={0.85} />
                      <Area type="monotone" dataKey="Gauche" stackId="1" stroke={BLOC_COLORS.Gauche} fill={BLOC_COLORS.Gauche} fillOpacity={0.85} />
                      <Area type="monotone" dataKey="RN"     stackId="1" stroke={BLOC_COLORS.RN}     fill={BLOC_COLORS.RN}     fillOpacity={0.85} />
                    </AreaChart>
                  </ResponsiveContainer>
                </div>
              );
            })}
          </div>

          <div className="mt-4 rounded-md border border-border bg-muted/40 px-4 py-3 text-xs text-muted-foreground">
            <strong>Lecture :</strong> le modèle reproduit dans le temps la logique économie → vote.
            En <strong className="text-emerald-700">scénario optimiste</strong>, l'économie atteint un
            « boom » → le vote bascule vers la <strong>Droite (Pécresse)</strong>. En
            <strong className="text-amber-700"> scénario pessimiste</strong>, la dégradation pousse d'abord
            vers la <strong>Gauche (Mélenchon)</strong>, puis vers le <strong>RN (Le Pen)</strong> en cas
            de crise. Le <strong>Centre (Macron)</strong> n'est majoritaire qu'en situation de stabilité.
            <br />
            <span className="italic">Méthode : {TEMPORAL_META.method}</span>
          </div>
        </SectionCard>

        {/* ╔══════ Summary stats ══════╗ */}
        <motion.section
          variants={itemVariant}
          className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"
        >
          {[
            { label: "Meilleur Modèle", value: "Logistic Reg.", sub: "76.76% accuracy" },
            { label: "Total Enregistrements", value: "858 024", sub: "Nouvelle-Aquitaine" },
            { label: "Variables Analysées", value: "28", sub: "Indicateurs delta + délinquance" },
            { label: "Classes Cibles", value: "5", sub: "Boom · Croissance · Stable · Déclin · Crise" },
          ].map((kpi, i) => (
            <motion.div
              key={kpi.label}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 * i }}
              className="rounded-md border border-border bg-card p-4 shadow-sm"
            >
              <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                {kpi.label}
              </p>
              <p className="mt-2 text-xl font-bold tracking-tight text-foreground">
                {kpi.value}
              </p>
              <p className="mt-1 text-xs text-muted-foreground">{kpi.sub}</p>
            </motion.div>
          ))}
        </motion.section>
      </motion.main>

      {/* Footer */}
      <footer className="border-t border-border py-6 text-center text-xs text-muted-foreground">
        GouvData · Analyse prédictive · Présidentielle 2022 ·
        Nouvelle-Aquitaine
      </footer>
    </div>
  );
}
